## GRID SEARCH

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(iris.data, iris.target)
sorted(clf.cv_results_.keys())

decision_function(X) //Call decision_function on the estimator with the best found parameters.

fit(X[, y, groups]) //Run fit with all sets of parameters.

get_params([deep]) //Get parameters for this estimator.

inverse_transform(Xt) //Call inverse_transform on the estimator with the best found params.

predict(X) //Call predict on the estimator with the best found parameters.

predict_log_proba(X) //Call predict_log_proba on the estimator with the best found parameters.

predict_proba(X) //Call predict_proba on the estimator with the best found parameters.

score(X[, y]) //Return the score on the given data, if the estimator has been refit.

score_samples(X) //Call score_samples on the estimator with the best found parameters.

set_params(**params) //Set the parameters of this estimator.

transform(X) //Call transform on the estimator with the best found parameters.

## CROSS - VALIDATION

In [ ]:
>>> from sklearn import datasets, linear_model
>>> from sklearn.model_selection import cross_validate
>>> from sklearn.metrics import make_scorer
>>> from sklearn.metrics import confusion_matrix
>>> from sklearn.svm import LinearSVC
>>> diabetes = datasets.load_diabetes()
>>> X = diabetes.data[:150]
>>> y = diabetes.target[:150]
>>> lasso = linear_model.Lasso()

## SINGLE MATRIC EVALUATION 
>>> cv_results = cross_validate(lasso, X, y, cv=3)
>>> sorted(cv_results.keys())
['fit_time', 'score_time', 'test_score']
>>> cv_results['test_score']
array([0.33150734, 0.08022311, 0.03531764])

## MULTI MATRIC EVALUATION
>>> scores = cross_validate(lasso, X, y, cv=3,
...                         scoring=('r2', 'neg_mean_squared_error'),
...                         return_train_score=True)
>>> print(scores['test_neg_mean_squared_error'])
[-3635.5... -3573.3... -6114.7...]
>>> print(scores['train_r2'])
[0.28010158 0.39088426 0.22784852]

## METRICS